security:
    firewalls:
        secured_area:
            pattern: ^/
            anonymous: ~
            http_basic:
                realm: "Recipes Admin"

    access_control:
        - { path: ^/recipes, roles: ROLE_ADMIN }
        - { path: ^/recipes$, roles: ROLE_ADMIN }

    providers:
        in_memory:
            memory:
                users:
                    admin: { password: admin, roles: 'ROLE_ADMIN' }


    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~

    encoders:
            Symfony\Component\Security\Core\User\User: plaintext